/**
 * BYOK codegen — the "nakli-ai routing" convention realized locally (handoff §12: a
 * convention, not a coupling). A prompt → a model module written against Lathe's model
 * contract, generated by the user's own cloud model (honest BYOK-cloud default, §Vision C1).
 *
 * The call goes straight from the browser to the AI provider with the user's key — no
 * Lathe server (there is none). The generated code is written into the editor and run
 * through the normal worker path; it is never eval'd here (rule #5). A bad generation
 * fails loud via the existing compile/build error path (G2).
 */
import { getKey } from "./vault";

const ENDPOINT = "https://api.anthropic.com/v1/messages";

/** Models offered in the BYOK picker. Default is the most capable (best CAD code). */
export const MODELS = [
  { id: "claude-opus-4-8", label: "Claude Opus 4.8" },
  { id: "claude-sonnet-4-6", label: "Claude Sonnet 4.6" },
  { id: "claude-haiku-4-5", label: "Claude Haiku 4.5" },
] as const;
export const DEFAULT_MODEL = MODELS[0].id;

const SYSTEM_PROMPT = `You write parametric CAD models for Lathe, a browser CAD tool where "the code is the model".

Output a JavaScript module with exactly two exports — nothing else:
  export const params = { ... };        // flat object of numbers/booleans/strings; these become UI controls
  export function build(p) { ... }       // receives the params, returns ONE shape (or an array of shapes)

The CAD API is available as globals — DO NOT import anything. All distances are millimetres.
Available functions (a shape is opaque; pass it around):
  box(width, depth, height)              // a box; its near-lower corner sits at the origin, extending +X/+Y/+Z
  cylinder(radius, height)               // axis along +Z, centred on the origin in XY, from z=0 to z=height
  sphere(radius)
  fuse(a, b)                             // union
  cut(base, tool)                        // subtract tool from base (e.g. drilling holes)
  intersect(a, b)
  fillet(shape, edges, radius)           // round edges; or fillet(shape, radius) for all edges
  chamfer(shape, edges, distance)        // bevel edges; or chamfer(shape, distance)
  translate(shape, [x, y, z])            // move a shape
  rotate(shape, angleDegrees, { axis: [x,y,z], center: [x,y,z] })
  scale(shape, factor)
  edgeFinder()                           // build an edge selector for fillet/chamfer; chain .inDirection([x,y,z])
  faceFinder()                           // face selector; chain .inDirection([x,y,z])

Rules:
- Booleans throw on bad geometry (no Result objects) — just call them directly.
- To round the vertical edges of a box: fillet(solid, edgeFinder().inDirection([0, 0, 1]), r).
- To drill a hole straight down through a plate of height h, centred at (x, y):
    cut(plate, translate(cylinder(r, h + 2), [x, y, -1]))     // over-length so it clears both faces
- "M4 hole" etc. = a clearance hole for an M-number metric bolt; use a radius slightly over half the M-number
  (e.g. M4 → ~2.2 mm radius, M3 → ~1.7 mm, M5 → ~2.7 mm).
- Make sensible parameters (sizes, counts, radii) so the part is adjustable from the panel.

Respond with ONLY one fenced \`\`\`js code block containing the module. No prose, no explanation.

Example — a 40×30×12 mounting bracket with a centred M5 hole and rounded corners:
\`\`\`js
export const params = { width: 40, depth: 30, height: 12, holeRadius: 2.7, cornerFillet: 3 };
export function build(p) {
  let solid = box(p.width, p.depth, p.height);
  if (p.cornerFillet > 0) solid = fillet(solid, edgeFinder().inDirection([0, 0, 1]), p.cornerFillet);
  const drill = translate(cylinder(p.holeRadius, p.height + 2), [p.width / 2, p.depth / 2, -1]);
  return cut(solid, drill);
}
\`\`\``;

interface GenerateOptions {
  model: string;
  prompt: string;
}

/** Generate a model module from a natural-language prompt. Returns the code (no fences). */
export async function generateModel({ model, prompt }: GenerateOptions): Promise<string> {
  const key = await getKey();
  if (!key) throw new Error("No API key set — add your Anthropic key first.");

  let res: Response;
  try {
    res = await fetch(ENDPOINT, {
      method: "POST",
      headers: {
        "content-type": "application/json",
        "x-api-key": key,
        "anthropic-version": "2023-06-01",
        // Opt in to direct browser calls (BYOK). The key still goes only to Anthropic.
        "anthropic-dangerous-direct-browser-access": "true",
      },
      body: JSON.stringify({
        model,
        max_tokens: 8192,
        thinking: { type: "adaptive" },
        system: SYSTEM_PROMPT,
        messages: [{ role: "user", content: prompt }],
      }),
    });
  } catch {
    throw new Error("Could not reach the AI provider — check your network and that the CSP allows api.anthropic.com.");
  }

  if (!res.ok) {
    throw new Error(await describeError(res));
  }

  const data = (await res.json()) as { content?: Array<{ type: string; text?: string }> };
  const text = (data.content ?? [])
    .filter((b) => b.type === "text" && typeof b.text === "string")
    .map((b) => b.text)
    .join("");
  const code = extractCode(text).trim();
  if (!code) throw new Error("The model returned no code. Try rephrasing the prompt.");
  return code;
}

/** Pull the first fenced code block; fall back to the whole text if unfenced. */
function extractCode(text: string): string {
  const fenced = /```(?:js|javascript|ts|typescript)?\s*\n([\s\S]*?)```/i.exec(text);
  return fenced ? fenced[1] : text;
}

async function describeError(res: Response): Promise<string> {
  let detail = "";
  try {
    const body = (await res.json()) as { error?: { message?: string } };
    detail = body.error?.message ? ` — ${body.error.message}` : "";
  } catch {
    /* non-JSON error body */
  }
  switch (res.status) {
    case 401:
      return "Invalid API key (401). Check the key and try again.";
    case 403:
      return "Key lacks permission for this model (403).";
    case 429:
      return "Rate limited (429). Wait a moment and retry.";
    case 529:
      return "The AI provider is overloaded (529). Retry shortly.";
    default:
      return `Generation failed (${res.status})${detail}`;
  }
}
